from datetime import timedelta
from typing import Any, Callable, Optional, Union

def cache(
    timeout: Union[int, timedelta], key_func: Optional[Callable] = ...
) -> Callable: ...
def memoize(*args, **kwargs) -> Callable: ...
def make_lookuper(func: Callable) -> Any: ...
def silent_lookuper(func: Callable) -> Any: ...
