from operator import itemgetter
from typing import Any, Callable, Type, Union

def make_func(f: Any, builtin: bool = ..., test: bool = ...) -> Any: ...
def make_pred(
    pred: Any, builtin: bool = ...
) -> Union[Type[bool], itemgetter, Callable]: ...
