from re import Pattern
from typing import Union

def re_iter(regex: Union[str, Pattern], s: str, flags: int = ...): ...
def re_all(regex: Union[str, Pattern], s: str, flags: int = ...): ...
def re_find(regex: Union[str, Pattern], s: str, flags: int = ...): ...
def re_test(regex: Union[str, Pattern], s: str, flags: int = ...): ...
def re_finder(regex: Union[str, Pattern], flags: int = ...): ...
def re_tester(regex: Union[str, Pattern], flags: int = ...): ...
def str_join(sep, seq=...): ...
def cut_prefix(s: str, prefix: str): ...
def cut_suffix(s: str, suffix: str): ...
