from typing import Any, Callable, Iterator

def tree_leaves(root, follow=Callable, children=Callable) -> Iterator[Any]: ...
def ltree_leaves(root, follow=Callable, children=Callable): ...
def tree_nodes(root, follow=Callable, children=Callable) -> Iterator[Any]: ...
def ltree_nodes(root, follow=Callable, children=Callable): ...
