name: Test Stubs
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [
          '3.7',
          '3.8',
          '3.9',
          '3.10'
        ]

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup PDM for Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@main
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: pdm install --dev

    - name: Run stubtest
      run: make stubtest
